---
# tasks file for roles/executor

- name: Create executor group
  become: yes
  group:
    name: "{{ executor_os_group }}"
    state: present

- name: Create executor user
  become: true
  user:
    name: "{{ executor_os_user }}"
    group: "{{ executor_os_group }}"
    state: present

- name: Write Executor Systemd unit file
  become: true
  template:
    src: executor-service.service
    dest: "{{ executor_systemd_unit_path }}"

- name: Create ~executor/.config/openstack dir
  become: true
  become_user: "{{ executor_os_user }}"
  file:
    dest: "~executor/.config/openstack/"
    state: directory
    recurse: true

- name: Create executor log dir
  become: true
  file:
    dest: /var/log/executor
    state: directory
    owner: "{{ executor_os_user }}"
    group: "{{ executor_os_group }}"

- name: Create executor config dir
  become: true
  file:
    dest: /etc/apimon_executor
    state: directory

- name: Write clouds.yaml
  become: true
  become_user: "{{ executor_os_user }}"
  copy:
    content: "{{ clouds_yaml_content }}"
    dest: "~executor/.config/openstack/clouds.yaml"

- name: Write env
  become: true
  become_user: "{{ executor_os_user }}"
  template:
    src: "env"
    dest: "~executor/env"

- name: Write logging config
  become: true
  become_user: "{{ executor_os_user }}"
  copy:
    src: logging.conf
    dest: /etc/apimon_executor/logging.conf

- name: Write executor config
  become: true
  become_user: "{{ executor_os_user }}"
  template:
    src: executor.yaml.j2
    dest: /etc/apimon_executor/executor.yaml

- name: Enable Executor Systemd service
  become: true
  become_user: "{{ executor_os_user }}"
  systemd:
    name: "{{ executor_systemd_service_name }}"
    enabled: true
    state: "started"
    daemon_reload: true
