---
# tasks file for roles/executor

- name: Include Fedora variables
  include_vars: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install required packages
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  register: task_result
  until: task_result is success
  retries: 5

- name: Create executor group
  become: yes
  group:
    name: "{{ executor_os_group }}"
    state: present

- name: Create executor user
  become: true
  user:
    name: "{{ executor_os_user }}"
    group: "{{ executor_os_group }}"
    state: present

- name: Write Executor Systemd unit file
  become: true
  template:
    src: executor.service
    dest: "{{ executor_systemd_unit_path }}"

- name: Create required directories
  become: true
  file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ executor_os_user }}"
    group: "{{ executor_os_group }}"
    recurse: true
  loop:
    - {dest: "/var/log/executor"}
    - {dest: "{{ executor_config_dir }}"}
    - {dest: "~executor/.config/openstack"}
    - {dest: "~executor/wrk"}

- name: Write clouds.yaml
  become: true
  become_user: "{{ executor_os_user }}"
  copy:
    content: "{{ clouds_yaml_content }}"
    dest: "~executor/.config/openstack/clouds.yaml"

- name: Write env
  become: true
  become_user: "{{ executor_os_user }}"
  template:
    src: "env"
    dest: "{{ executor_config_dir }}/env"
  notify:
    - restart executor

- name: Write logging config
  become: true
  become_user: "{{ executor_os_user }}"
  copy:
    src: logging.conf
    dest: "{{ executor_log_config_location }}"
  notify:
    - restart executor

- name: Write executor config
  become: true
  become_user: "{{ executor_os_user }}"
  template:
    src: executor.yaml.j2
    dest: "{{ executor_config_location }}"
  when: executor_config_content is not defined
  notify:
    - restart executor

- name: Write executor config
  become: true
  become_user: "{{ executor_os_user }}"
  copy:
    content: "{{ executor_config_content }}"
    dest: "{{ executor_config_location }}"
  when: (executor_config_content is defined) and (executor_config_content|length > 0)
  notify:
    - restart executor
