---
# tasks file for apimon_executor

- when: executor_host_state != 'absent'
  block:

    - name: Create Data Volume {{ executor_host_data_volume_name }}
      os_volume:
        state: "{{ executor_host_state }}"
        name: "{{ executor_host_data_volume_name }}"
        size: "{{ executor_host_data_volume_size }}"
        volume_type: "{{ executor_host_data_volume_type | default(omit) }}"
        availability_zone: "{{ executor_host_availability_zone }}"
        metadata: "{{ executor_host_data_volume_metadata }}"
        wait: true
      when: executor_host_data_volume_size is defined
      register: data_volume

    - name: Create Var Volume {{ executor_host_var_volume_name }}
      os_volume:
        state: "{{ executor_host_state }}"
        name: "{{ executor_host_var_volume_name }}"
        size: "{{ executor_host_var_volume_size }}"
        volume_type: "{{ executor_host_var_volume_type | default(omit) }}"
        availability_zone: "{{ executor_host_availability_zone }}"
        metadata: "{{ executor_host_var_volume_metadata }}"
        wait: true
      when: executor_host_var_volume_size is defined
      register: var_volume

    - name: Create server {{ executor_host_server_name }}
      os_server:
        state: "{{ executor_host_state }}"
        name: "{{ executor_host_server_name }}"
        image: "{{ executor_host_image }}"
        flavor: "{{ executor_host_flavor }}"
        key_name: "{{ executor_host_key_name }}"
        boot_from_volume: true
        auto_ip: "{{ executor_host_auto_ip }}"
        meta: "{{ executor_host_metadata }}"
        availability_zone: "{{ executor_host_availability_zone }}"
        security_groups: "{{ executor_host_security_groups }}"
        nics: "{{ executor_host_network }}"
        volume_size: "{{ executor_host_root_volume_size }}"
        volumes:
          - "{{ data_volume.id }}"
          - "{{ var_volume.id }}"
        userdata: |
          #cloud-config
          fqdn: {{ executor_host_server_fqdn }}
          packages:
          growpart:
            mode: auto
            devices: ['/']
            ignore_growroot_disabled: false
          disk_setup:
            /dev/vdb:
              table_type: 'mbr'
              layout:
               - 100
            /dev/vdc:
              table_type: 'mbr'
              layout:
               - 100

          fs_setup:
            - label: home
              filesystem: ext4
              device: '/dev/vdb1'
            - label: var
              filesystem: ext4
              device: '/dev/vdc1'

          mounts:
            - [ "LABEL=home", "/home", "auto", "defaults", "0", "2" ]
            - [ "LABEL=var", "/var", "auto", "defaults", "0", "2" ]

      register: server

- when: executor_host_state == 'absent'
  block:

    - name: Delete host
      os_server:
        state: absent
        name: "{{ executor_host_server_name }}"

    - name: Delete data volume
      os_volume:
        state: absent
        name: "{{ executor_host_data_volume_name }}"

    - name: Delete var volume
      os_volume:
        state: absent
        name: "{{ executor_host_var_volume_name }}"
